#!/bin/bash
set -euo pipefail

# =============================================================================
# crabRave.sh - Dispatcher for CRAB job submission across all steps and runs.
#
# Usage:
#   ./crabRave.sh -Run3 -GENSIM
#   ./crabRave.sh -Run3 -DIGIHLT -batch 1
#   ./crabRave.sh -Run2 -RAWSIM
#
# Optional: -batch 1  (submit first half)
#           -batch 2  (submit second half)
#
# Run2 intermediate steps (HLTSIM, MINIAODSIM) read input file lists from
# WTTR discovery files generated by ravePregame.sh, since xrdfs is not
# available inside the VM.
# =============================================================================

source "$(dirname "${BASH_SOURCE[0]}")/../config/common.sh"

if [[ $# -lt 2 ]]; then
    echo "Usage: ./crabRave.sh -Run<#> -STEP [-batch 1|2]"
    echo ""
    usage_steps
    echo ""
    echo "  -batch 1  Submit first half of jobs only"
    echo "  -batch 2  Submit second half of jobs only"
    exit 1
fi

parse_run "$1"; shift
parse_step "$1"; shift
load_step_config

# --- Parse -batch ---
BATCH=""
if [[ $# -ge 2 ]] && [[ "$1" == "-batch" ]]; then
    if [[ "$2" == "1" || "$2" == "2" ]]; then
        BATCH="$2"
    else
        echo "ERROR: -batch requires 1 or 2 (got '$2')" >&2
        exit 1
    fi
fi

# =============================================================================
# Pre-flight checks
# =============================================================================
cd "$SUBMISSION_DIR"

echo "crabRave: running ${RUN} ${STEP} from ${SUBMISSION_DIR}"
echo ""

for tmpl in "$TMPL_CFG_PATH" "$TMPL_CRAB_PATH"; do
    if [[ ! -f "$tmpl" ]]; then
        echo "ERROR: template file '${tmpl}' not found." >&2
        exit 1
    fi
done

if [[ "$INPUT_MODE" == "GENSIM_MODE" ]] && [[ ! -f "$TMPL_LHE_PATH" ]]; then
    echo "ERROR: template file '${TMPL_LHE_PATH}' not found." >&2
    exit 1
fi

if [[ "$INPUT_MODE" == "WTTR_MODE" ]] && [[ ! -f "$WTTR_PATH" ]]; then
    echo "ERROR: discovery file '${WTTR_PATH}' not found." >&2
    echo "  Run ravePregame.sh for this step first (outside the VM)." >&2
    exit 1
fi

if ! command -v crab &>/dev/null; then
    echo "ERROR: 'crab' command not found. Source the CRAB environment first." >&2
    exit 1
fi

if [[ "$INPUT_MODE" == "EOS_MODE" ]] && ! command -v xrdfs &>/dev/null; then
    echo "ERROR: 'xrdfs' command not found." >&2
    exit 1
fi

REGISTRY="${SUBMISSION_DIR}/submit_registry_${STEP}.log"
if [[ ! -f "$REGISTRY" ]]; then
    echo "# crabRave ${RUN} ${STEP} registry - $(date)" > "$REGISTRY"
    echo "# jobTag | inputRef | submitTime | status" >> "$REGISTRY"
fi

# =============================================================================
# Helper: clean up working copies
# =============================================================================
cleanup() {
    rm -f "$WORK_CFG" "$WORK_CRAB"
    if [[ "$INPUT_MODE" == "GENSIM_MODE" ]]; then
        rm -f "$WORK_LHE_SH"
    fi
}

trap cleanup EXIT

# =============================================================================
# Main loop
# =============================================================================
job_num=0

for ct in "${ct_values[@]}"; do
    for mzd in "${mzd_values[@]}"; do
        job_num=$(( job_num + 1 ))

        # Batch mode: skip jobs outside the selected half
        half=$(( (TOTAL_JOBS + 1) / 2 ))
        if [[ -n "$BATCH" ]]; then
            if [[ "$BATCH" == "1" ]] && (( job_num > half )); then
                continue
            elif [[ "$BATCH" == "2" ]] && (( job_num <= half )); then
                continue
            fi
        fi

        mzd_safe="${mzd/./p}"
        ct_safe="${ct/./p}"
        job_tag="${STEP}_mzd_${mzd_safe}_ct_${ct_safe}"

        echo "=========================================="
        echo " Job ${job_num}/${TOTAL_JOBS}"
        echo " Job tag  : ${job_tag}"
        echo "=========================================="

        if grep -q "^${job_tag}|" "$REGISTRY" 2>/dev/null; then
            if grep -q "^${job_tag}|.*|FAILED$" "$REGISTRY" 2>/dev/null; then
                echo "RETRY: ${job_tag} previously failed. Cleaning up and resubmitting."
                sed -i "/^${job_tag}|/d" "$REGISTRY"
                crab_dir="work/crab_${job_tag}"
                if [[ -d "$crab_dir" ]]; then
                    rm -rf "$crab_dir"
                    echo "Removed: ${crab_dir}"
                fi
            else
                echo "SKIP: ${job_tag} already in registry. Moving on."
                echo ""
                continue
            fi
        fi

        # --- GENSIM_MODE: stamp cfg, crab config, and staging script ---
        if [[ "$INPUT_MODE" == "GENSIM_MODE" ]]; then
            lhe_file="mzd_${mzd}_ct_${ct}.lhe"
            echo " LHE file : ${lhe_file}"

            sed "s|PLACEHOLDER_LHE|${lhe_file}|g" "$TMPL_LHE_PATH"  > "$WORK_LHE_SH"
            sed "s|PLACEHOLDER_LHE|${lhe_file}|g" "$TMPL_CFG_PATH"   > "$WORK_CFG"
            sed "s|PLACEHOLDER_JOBTAG|${job_tag}|g" "$TMPL_CRAB_PATH" > "$WORK_CRAB"
            chmod +x "$WORK_LHE_SH"
            input_ref="$lhe_file"

        # --- WTTR_MODE: read inputs from pregame discovery file ---
        elif [[ "$INPUT_MODE" == "WTTR_MODE" ]]; then
            echo "Reading inputs from ${WTTR_FILE}..."

            wttr_line=$(grep "^${job_tag}|" "$WTTR_PATH" || true)

            if [[ -z "$wttr_line" ]]; then
                echo "ERROR: no entry for ${job_tag} in ${WTTR_FILE}." >&2
                echo "  Re-run ravePregame.sh for this step." >&2
                trap - EXIT
                exit 1
            fi

            input_list=$(echo "$wttr_line" | cut -d'|' -f2)
            echo "Found inputs from discovery file."

            output_root="mzd_${mzd_safe}_ct_${ct_safe}.root"

            sed "s|PLACEHOLDER_JOBTAG|${job_tag}|g" "$TMPL_CRAB_PATH"    | \
            sed "s|PLACEHOLDER_OUTPUTROOT|${output_root}|g"                > "$WORK_CRAB"

            sed "s|PLACEHOLDER_OUTPUTROOT|${output_root}|g" "$TMPL_CFG_PATH" > "$WORK_CFG"

            python3 -c "
with open('${WORK_CRAB}', 'r') as f:
    content = f.read()
content = content.replace('PLACEHOLDER_INPUTFILES', '''${input_list}''')
with open('${WORK_CRAB}', 'w') as f:
    f.write(content)
"
            input_ref="WTTR"

        # --- EOS_MODE: discover inputs from EOS ---
        else
            input_tag="${INPUT_TAG_PREFIX}_mzd_${mzd_safe}_ct_${ct_safe}"
            input_dir="${INPUT_BASE}/${input_tag}"
            echo " Input tag : ${input_tag}"
            echo "Querying EOS: ${input_dir}..."

            timestamp_path=$(xrdfs "$EOS_REMOTE" ls "$input_dir" 2>/dev/null | head -n 1 || true)

            if [[ -z "$timestamp_path" ]]; then
                echo "ERROR: no timestamp directory found for ${input_tag}." >&2
                echo "  Check that ${INPUT_TAG_PREFIX} jobs completed before running this step." >&2
                trap - EXIT
                exit 1
            fi

            echo "Found: ${timestamp_path}"

            mapfile -t root_files < <(xrdfs "$EOS_REMOTE" ls "${timestamp_path}/0000" 2>/dev/null | grep '\.root$' || true)

            if [[ ${#root_files[@]} -eq 0 ]]; then
                echo "ERROR: no ROOT files found under ${timestamp_path}/0000 for ${input_tag}." >&2
                trap - EXIT
                exit 1
            fi

            echo "Found ${#root_files[@]} ROOT file(s)."

            input_list="["
            for f in "${root_files[@]}"; do
                input_list+="'${f}', "
            done
            input_list="${input_list%, }]"

            output_root="mzd_${mzd_safe}_ct_${ct_safe}.root"

            sed "s|PLACEHOLDER_JOBTAG|${job_tag}|g" "$TMPL_CRAB_PATH"    | \
            sed "s|PLACEHOLDER_OUTPUTROOT|${output_root}|g"                > "$WORK_CRAB"

            sed "s|PLACEHOLDER_OUTPUTROOT|${output_root}|g" "$TMPL_CFG_PATH" > "$WORK_CFG"

            python3 -c "
with open('${WORK_CRAB}', 'r') as f:
    content = f.read()
content = content.replace('PLACEHOLDER_INPUTFILES', '''${input_list}''')
with open('${WORK_CRAB}', 'w') as f:
    f.write(content)
"
            input_ref="$input_tag"
        fi

        # --- Submit ---
        echo "Submitting CRAB job..."
        if crab submit -c "$WORK_CRAB"; then
            submit_time="$(date '+%Y-%m-%d %H:%M:%S')"
            echo "${job_tag}|${input_ref}|${submit_time}|SUCCESS" >> "$REGISTRY"
            echo "SUCCESS: ${job_tag} submitted at ${submit_time}"
        else
            submit_time="$(date '+%Y-%m-%d %H:%M:%S')"
            echo "${job_tag}|${input_ref}|${submit_time}|FAILED" >> "$REGISTRY"
            echo "" >&2
            echo "============================================" >&2
            echo " SUBMIT FAILED: ${job_tag}" >&2
            echo " Input ref   : ${input_ref}" >&2
            echo " Job number  : ${job_num}/${TOTAL_JOBS}" >&2
            echo "" >&2
            echo " Working copy preserved for debugging:" >&2
            echo "   ${WORK_CRAB}" >&2
            echo "============================================" >&2
            trap - EXIT
            exit 1
        fi

        echo ""
    done
done

echo "=========================================="
if [[ -n "$BATCH" ]]; then
    echo " Batch ${BATCH} of ${RUN} ${STEP} jobs submitted successfully!"
else
    echo " All ${TOTAL_JOBS} ${RUN} ${STEP} jobs submitted successfully!"
fi
echo " Registry: ${REGISTRY}"
echo "=========================================="
